### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by Alenhasha** [andwatson/interseismic_practical#7]
How have you prepared the usage data?
 For example, why is the volume of your data less compared to the LICSBAS results and outputs?

**Comment by andwatson** [comment]
The input data are the generic float outputs that LiCSBAS creates in its "results" directory. If I'm remembering correctly, they were generated using a 20x multilook factor so as to keep the files small for Binder. Does that answer your question?

**Comment by Alenhasha** [comment]
yes, thank you very much.
